version: 2

sources:
  - name: humanresources
    schema: humanresources
    tables:
     - name: employee
     - name: department
     - name: shift
  - name: person
    schema: person
    tables:
      - name: person
  - name: production
    schema: production
    tables:
      - name: product
      - name: productcategory
      - name: productsubcategory
  - name: purchasing
    schema: purchasing
    tables:
      - name: shipmethod



models:
  - name: stg_employee
    columns:
      - name: employee_id
        description: "A unique identifier for the employee"
        tests:
          - unique
          - not_null
  - name: stg_product
    columns:
      - name: product_ID
        description: "A unique identifier for the product"
        tests:
          - unique
          - not_null
  - name: stg_shipment
    columns:
      - name: shipment_ID
        description: "A unique identifier for the shipment company"
        tests:
          - unique
          - not_null            
