version: 2

models:
  - name: fct_purchasing
    description: Fact table for purchasing. Each record represents the state of a purchasing between the dates `valid_from` and `valid_to`.
    columns:
      - name: purchase_id
        description: "A unique identifier for the shipment company"
        tests:
          - unique
          - not_null
      - name: sk_vendor
        description: "A unique identifier for the vendor"
        tests:
          - unique
          - not_null
      - name: sk_employee
        description: "A unique identifier for the employee"
        tests:
          - unique
          - not_null
      - name: sk_product
        description: "A unique identifier for the product"
        tests:
          - unique
          - not_null
      - name: sk_shipment
        description: "A unique identifier for the shipment company"
        tests:
          - unique
          - not_null
      - name: sk_order_date
        description: "Date of order"
      - name: sk_shipment_date
        description: "Date of shipment"
      - name: ship_satus
        description: "Shipment status"
      - name: due_date
        description: "Date the product is expected to be received."
      - name: orderqty
        description: "Order quantity"
      - name: qty_received
        description: "Received quantity"
      - name: unit_price
        description: "Single product price"
      - name: product_total
        description: "Total price for product"
      - name: order_subtotal
        description: "Purchase order subtotal."
      - name: tax_amount
        description: "Tax amount"
      - name: freight
        description: "Shipping cost"
      - name: order_total
        description: "Total amount for order"
        
  - name: dim_date
    description: Date dimension table
  - name: dim_employee
    description: Dimension table for the employees. Each record represents the state of an employee between the dates `valid_from` and `valid_to`.
    columns:
      - name: sk_employee
        description: "A unique identifier for this record in the table"
        tests:
          - unique
          - not_null
      - name: employee_id
        description: "A unique identifier for the employee"
      - name: first_name
        description: "employee first name"
      - name: middle_name
        description: "employee midle name"
      - name: last_name
        description: "employee last name"
      - name: birth_date
        description: "Date of birth"
      - name: gender
        description: "Gender"
      - name: email
        description: "email of employee"  
      - name: job_title
        description: "The job title of the employee"
      - name: organization_node
        description: "The building block from the organization"
      - name: valid_from
        description: "This record is valid since this datetime."
      - name: valid_to
        description: "This record is valid until this datetime."
      - name: last_updated_at
        description: "Timestamp of the last update to this record."
  - name: dim_product
    description: Dimension table for the products. Each record represents the state of a product between the dates `valid_from` and `valid_to`.
    columns:
      - name: sk_product
        description: "A unique identifier for this record in the table"
        tests:
          - unique
          - not_null
      - name: product_id
        description: "A unique identifier for the product"
      - name: product_name
        description: "The name of the product"
      - name: product_number
        description: "The number of the product"
      - name: category
        description: "The category of the product"
      - name: subcategory
        description: "The subcategory of the product"
      - name: color
        description: " The color of the product"
      - name: size
        description:	"The size of the product"
      - name: weight
        description: "The weight of the product"
      - name: valid_from
        description: "This record is valid since this datetime."
      - name: valid_to
        description: "This record is valid until this datetime."
      - name: last_updated_at
        description: "Timestamp of the last update to this record."
  - name: dim_shipment
    description: Dimension table for the shipment companies. Each record represents the state of a shipment between the dates `valid_from` and `valid_to`.
    columns:
      - name: sk_shipment
        description: "A unique identifier for this record in the table"
        tests:
          - unique
          - not_null
      - name: shipment_ID
        description: "A unique identifier for the product"
      - name: name
        description: "The name of the shipment"
      - name: min_ship_charge
        description: "Minimum amount charged"
      - name: pound_ship_charge
        description: "Price per pound"
      - name: modified_date
        description: "Date of modification"
      - name: valid_from
        description: "This record is valid since this datetime."
      - name: valid_to
        description: "This record is valid until this datetime."
      - name: last_updated_at
        description: "Timestamp of the last update to this record."
  - name: dim_vendor
    description: Dimension table for the vendors. Each record represents the state of a vendor between the dates `valid_from` and `valid_to`.
    columns:
      - name: sk_vendor
        description: "A unique identifier for this record in the table"
        tests:
          - unique
          - not_null
      - name: vendor_ID
        description: "A unique identifier for the vendor"
      - name: name
        description: "The name of the vendor"
      - name: account_number
        description: "Number of the account"
      - name: product_id
        description: "Id of the product"
      - name: standard_price
        description: "Standard price of product"
      - name: city
        description: "city of vendor"
      - name: state_province
        description: "state province of vendor"
      - name: country
        description: "country of vendor"
      - name: valid_from
        description: "This record is valid since this datetime."
      - name: valid_to
        description: "This record is valid until this datetime."
      - name: last_updated_at
        description: "Timestamp of the last update to this record."