version: 2

models:
  - name: dim_date
    description: Date dimension table
  - name: dim_employee
    description: >
      Dimension table for the employees. Each record represents the state of
      an employee between the dates `valid_from` and `valid_to`.
    columns:
      - name: sk_employee
        description: "A unique identifier for this record in the table"
        tests:
          - unique
          - not_null
      - name: employee_id
        description: "A unique identifier for the employee"
      - name: job_title
        description: "The job title of the employee"
      - name: birth_date
        description: "Date of birth"
      - name: gender
        description: "Gender"
      - name: organization_node
        description: "The building block from the organization"
      - name: employee_row_guid
        description: " number uniquely identifying the record"
      - name: employee_last_update
        description:	"Date and time the record was last updated"
      - name: first_name
        description: "employee first name"
      - name: middle_name
        description: "employee midle name"
      - name: last_name
        description: "employee last name"
      - name: person_row_guid
        description: "number uniquely identifying the record"
      - name: person_last_update
        description: "Date and time the record was last updated"
      - name: valid_from
        description: "This record is valid since this datetime."
      - name: valid_to
        description: "This record is valid until this datetime."
      - name: last_updated_at
        description: "Timestamp of the last update to this record."
